field: 9f6d5827-cbea-40ba-855a-7b6e6168d46e # recept inhoud
fieldLayouts:
  53f1efd4-e964-49da-b76a-ec4936baf0d8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2c08307b-8cc5-4a85-8a78-046b10e40851 # body content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9268eeb3-e9d4-4816-a491-a65acef83b82
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9e271694-4bf4-4ced-9114-edd00babae43
        userCondition: null
fields:
  2c08307b-8cc5-4a85-8a78-046b10e40851: # body content
    columnSuffix: gdxvdxsy
    contentColumnType: text
    fieldGroup: null
    handle: bodyContent
    instructions: null
    name: 'body content'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      purifierConfig: Default.json
      purifyHtml: true
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      tinymceConfig: Default.json
    translationKeyFormat: null
    translationMethod: none
    type: abmat\tinymce\Field
handle: receptInfo
name: 'recept info'
sortOrder: 2
