fieldLayouts:
  8c7649d4-68e0-4ae7-9d40-6503790fa331:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: 'recept naam'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2458b9b1-a8b7-4876-9a24-7800eb39e203
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8da4d8b0-06d5-4000-88b3-6d37af04c49c # introduction
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3aa38ce1-6cbf-4b67-8baa-f2732b7a476d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7de9a02c-50a5-4498-b039-9f4ffb040df1 # banner image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fbed818b-a6af-46a0-83a6-a916e585c15d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5542f6b0-e0b0-414b-9d83-6eb78b5c878c
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 88d40977-01e3-4486-9f9c-fd72554f9e38 # recept
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
