fieldLayouts:
  e8dd2749-8d23-49b1-8c90-302a4cbae9ea:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 40c9d21c-a46d-4589-a6a2-4def1658b266
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4ae10350-6af6-4fee-8bb1-b2ad8abdf8c6
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 45f4b5c1-1aa9-41b3-b642-6e387d537078 # Store Categories
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
