fieldLayouts:
  0c6bf69b-4517-46d9-b61f-b3c404175073:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2c9b41f1-85a9-4e55-bc09-9036d6d716d9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 564caf4f-fd90-4ca0-aa9e-be92753bc0f6 # Rich Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 702c8580-dcde-4cef-9e24-38acc9fb2bd0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 83d6e0d9-cf84-4c14-ad0c-5ca06cc46508
        userCondition: null
handle: header
hasTitleField: false
name: header
section: b419bd2b-ec55-4113-9035-024006bed5d4 # header
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
