context: global
field: 9f6d5827-cbea-40ba-855a-7b6e6168d46e # recept inhoud
fieldLayout: null
groupName: Text
groupSortOrder: 2
matrixBlockType: 60959cef-65c7-402d-a931-059debbc85b8 # recept sluitzin
sortOrder: 3
