context: global
field: 9f6d5827-cbea-40ba-855a-7b6e6168d46e # recept inhoud
fieldLayout: null
groupName: Extra
groupSortOrder: 3
matrixBlockType: fa8f5507-219d-4c04-97e7-db5a7b02a5d3 # recept beoordeling
sortOrder: 2
