context: global
field: 9f6d5827-cbea-40ba-855a-7b6e6168d46e # recept inhoud
fieldLayout: null
groupName: Tabel
groupSortOrder: 1
matrixBlockType: 627bc7e4-85f0-49a0-b502-22943fe616f5 # recept ingrediënten
sortOrder: 1
