context: global
field: 9f6d5827-cbea-40ba-855a-7b6e6168d46e # recept inhoud
fieldLayout: null
groupName: Text
groupSortOrder: 2
matrixBlockType: 3d17f45f-9f65-418f-b340-280cc872a3e9 # recept tip
sortOrder: 2
