context: global
field: 9f6d5827-cbea-40ba-855a-7b6e6168d46e # recept inhoud
fieldLayout: null
groupName: Tabel
groupSortOrder: 1
matrixBlockType: db3e3c94-bf5a-45d1-94aa-0445068695e4 # recept bereiding
sortOrder: 2
