context: global
field: 9f6d5827-cbea-40ba-855a-7b6e6168d46e # recept inhoud
fieldLayout: null
groupName: Text
groupSortOrder: 2
matrixBlockType: ddd8e4ca-c7e2-441d-93e0-eac1b0cfea81 # recept info
sortOrder: 1
