fieldLayouts:
  6e0305fa-3c53-44a7-8339-1de59921d6df:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 8cf920ee-164e-4dc9-b332-401d1452ba47
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: f9827f72-1aff-4507-9043-f3db2dd7afcc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0ed80b2a-952e-463c-b200-00c31b46d2dd
        userCondition: null
fs: a1
handle: reclameAssets
name: 'reclame assets'
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: a1
transformSubpath: ''
