dateModified: 1703880150
email:
  fromEmail: r0936750@student.thomasmore.be
  fromName: DrankenParadijs
  transportType: craft\mail\transportadapters\Sendmail
fs:
  a1:
    hasUrls: true
    name: a1
    settings:
      path: '@webroot/images'
    type: craft\fs\Local
    url: '@web/images'
  assets:
    hasUrls: true
    name: assets
    settings:
      path: '@webroot/images'
    type: craft\fs\Local
    url: '@web/images'
  assets1:
    hasUrls: true
    name: assets1
    settings:
      path: '@webroot/images'
    type: craft\fs\Local
    url: '@web/images'
  assets2:
    hasUrls: true
    name: assets2
    settings:
      path: '@webroot/images'
    type: craft\fs\Local
    url: '@web/images'
meta:
  __names__:
    2f168f32-022e-41b6-b829-e8227dcba32f: Default # Default
    3a1b225f-b8dd-4af7-9891-def9e4c15675: 'reclame assets' # reclame assets
    5d527726-39bd-41f1-b851-6569cba7cf81: 'recept assets' # recept assets
    7de9a02c-50a5-4498-b039-9f4ffb040df1: 'banner image' # banner image
    8da4d8b0-06d5-4000-88b3-6d37af04c49c: introduction # introduction
    24ba44f8-b163-4a93-8ae6-d273399f4d9b: 'about us' # about us
    27bd3e43-7316-4a7d-a87c-26613e63cd50: footer # footer
    34eb7326-076c-456e-8d24-03592761349c: footer # footer
    66f675c8-f9df-422a-99df-d1a23aa561da: reclame # reclame
    88d40977-01e3-4486-9f9c-fd72554f9e38: recept # recept
    89f003ec-2127-4003-b52c-afad58cb98ea: Common # Common
    89ff642d-5930-4155-b63c-9b4051268d27: 'about us' # about us
    90dfda7e-1fd7-40f2-9a39-e0ebe9a0257c: DrankenParadijs # DrankenParadijs
    219fbfdb-06e6-41ff-809a-590e5ac34411: 'full text' # full text
    564caf4f-fd90-4ca0-aa9e-be92753bc0f6: 'Rich Text' # Rich Text
    a5f087e4-a3b3-454e-90e3-43620b2a61ff: Default # Default
    ace54ebe-7118-4e76-9672-0cfe7d4679bc: DrankenParadijs # DrankenParadijs
    b419bd2b-ec55-4113-9035-024006bed5d4: header # header
    bfb57871-957a-42da-a4bf-dada052637a2: 'banner image' # banner image
    de2a990d-7bbb-45fd-8538-c3aa9d2aee51: header # header
plugins:
  abm-tinymce:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: DrankenParadijs
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
