defaultPlacement: end
enableVersioning: true
handle: aboutUs
name: 'about us'
propagationMethod: all
siteSettings:
  ace54ebe-7118-4e76-9672-0cfe7d4679bc: # DrankenParadijs
    enabledByDefault: true
    hasUrls: true
    template: about-us/_entry
    uriFormat: about-us
type: single
