defaultPlacement: end
enableVersioning: true
handle: assortiment
name: assortiment
propagationMethod: all
siteSettings:
  ace54ebe-7118-4e76-9672-0cfe7d4679bc: # DrankenParadijs
    enabledByDefault: true
    hasUrls: true
    template: assortiment/_entry
    uriFormat: 'assortiment/{slug}'
type: channel
