defaultPlacement: end
enableVersioning: true
handle: footer
name: footer
propagationMethod: all
siteSettings:
  ace54ebe-7118-4e76-9672-0cfe7d4679bc: # DrankenParadijs
    enabledByDefault: true
    hasUrls: true
    template: footer/_entry
    uriFormat: footer
type: single
