defaultPlacement: end
enableVersioning: true
handle: header
name: header
propagationMethod: all
siteSettings:
  ace54ebe-7118-4e76-9672-0cfe7d4679bc: # DrankenParadijs
    enabledByDefault: true
    hasUrls: true
    template: header/_entry
    uriFormat: header
type: single
