defaultPlacement: end
enableVersioning: true
handle: reclame
name: reclame
propagationMethod: all
siteSettings:
  ace54ebe-7118-4e76-9672-0cfe7d4679bc: # DrankenParadijs
    enabledByDefault: true
    hasUrls: true
    template: reclame/_entry
    uriFormat: 'reclame/{slug}'
type: channel
