defaultPlacement: end
enableVersioning: true
handle: storeCategories
name: 'Store Categories'
propagationMethod: all
siteSettings:
  ace54ebe-7118-4e76-9672-0cfe7d4679bc: # DrankenParadijs
    enabledByDefault: true
    hasUrls: true
    template: store-categories/_entry
    uriFormat: 'store-categories/{slug}'
structure:
  maxLevels: null
  uid: 960635ae-c715-4661-b935-3be5eb90e1cb
type: structure
